# .travis.yml for haystack

language: python

python:
  - "2.7"
  - "3.5"

# we are using pre-dumped tests files
# and not testing the dumping capacity of haystack.
# travis-ci does not support llvm 3.7 yet, so lets not put a bunch
# of dependencies due to ctypeslib2.
# this test will start from already existing ctypeslib2 generated files.
# system python package will not be used. http://docs.travis-ci.com/user/languages/python/.
# numpy is already installed
# we can use containers.

sudo: false

# travis-ci upgrades it. so it is already there.
#addons:
#  apt:
#    packages:
#    - unzip

# install any dependencies required
install:
## we need coveralls
  - pip -q install coveralls
## install with requirements
  - pip install -r requirements.txt --use-mirrors

before_script:
# we also need the large test files (memory dumps)
  - mkdir -p test/dumps/putty
  - mkdir -p test/dumps/ssh
  - mkdir -p test/dumps/vol
  - mkdir -p test/dumps/minidump
# win7 x32
  - wget https://www.dropbox.com/s/ez2t8u0ewzpvfay/putty.1.dump.zip
  - unzip -q putty.1.dump.zip
  - mv putty.1.dump test/dumps/putty/
  - wget https://www.dropbox.com/s/heornlu0bljbegs/putty.7124.dump.zip
  - unzip -q putty.7124.dump.zip
  - mv putty.7124.dump test/dumps/putty/
# win7 x64
  - wget https://www.dropbox.com/s/1b6xytpvbpabg7b/keepass.test.zip
  - unzip -q keepass.test.zip
  - mv keepass.test test/dumps/
# linux
  - wget https://www.dropbox.com/s/wprgq98hcv9kxsx/ssh.1.tgz
  - tar zxf ssh.1.tgz
  - mv ssh.1 test/dumps/ssh/
  - wget https://www.dropbox.com/s/oh227t9jzh9ydh1/ssh.x64.6653.dump.tgz
  - tar zxf ssh.x64.6653.dump.tgz
  - mv ssh.x64.6653.dump test/dumps/ssh/
# process extracted from volatility
  - wget https://www.dropbox.com/s/1g3ywwpqv5bg5za/zeus.vmem.1668.dump.zip
  - unzip -P infected zeus.vmem.1668.dump.zip
  - mv zeus.vmem.1668.dump test/dumps/vol/
  - wget https://www.dropbox.com/s/aj5sy48imxr9kwz/zeus.vmem.856.dump.zip
  - unzip -P infected zeus.vmem.856.dump.zip
  - mv zeus.vmem.856.dump test/dumps/vol/
# winxp 64
  - wget https://www.dropbox.com/s/8x28lgd6ljgjitl/cmd.dmp.gz
  - gunzip cmd.dmp.gz
  - mv cmd.dmp test/dumps/minidump
  - wget https://www.dropbox.com/s/emj1mh86bdep51c/alg.dmp.gz
  - gunzip alg.dmp.gz
  - mv alg.dmp test/dumps/minidump
# we need the simple memory tests.
  - wget https://www.dropbox.com/s/71meb0a1lck1u2c/src-39ec8f580ac133a317fb746bb303b1263857d2f0.tgz
  - tar zxf src-39ec8f580ac133a317fb746bb303b1263857d2f0.tgz -C test/


script:
# run tests. Need root for memory dumps tests.
#  - python setup.py test
  - coverage run --source=haystack setup.py test

after_success:
  - coveralls

after_failure:
  - coveralls
  - find

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never


